# Generated by Django 4.0.4 on 2022-11-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='projects/completed')),
                ('date', models.DateTimeField(auto_now=True)),
                ('des', models.TextField(blank=True)),
                ('start', models.DateField(auto_now=True)),
                ('end', models.DateField(auto_now=True)),
                ('lang', models.TextField(blank=True)),
                ('Platform', models.TextField(blank=True)),
            ],
        ),
    ]
