# Generated by Django 4.0.4 on 2022-11-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('des', models.TextField()),
                ('img', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
                ('source', models.TextField()),
                ('source_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='add_content_to_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
                ('des', models.TextField(blank=True)),
                ('blog_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blog')),
            ],
        ),
    ]
