# Generated by Django 4.0.4 on 2022-11-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_blog_add_content_to_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_catogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_catogorys_name', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('des', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.blog_catogory', unique=True),
        ),
    ]
