# Generated by Django 4.0.4 on 2022-11-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_blog_catogory_blog_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='under',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blog_catogory'),
        ),
    ]
