# Generated by Django 4.0.4 on 2022-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_blog_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
                ('title', models.TextField(blank=True)),
                ('des', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
