# Generated by Django 4.0.4 on 2022-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_content_to_blog',
            name='youtubeLink',
            field=models.URLField(blank=True),
        ),
    ]
