# Generated by Django 4.0.4 on 2022-11-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_add_content_to_blog_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_content_to_blog',
            name='image_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ListOfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageSelect', models.ImageField(blank=True, upload_to='')),
                ('imageUrl', models.ImageField(blank=True, upload_to='')),
                ('blogPostNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.add_content_to_blog')),
            ],
        ),
        migrations.CreateModel(
            name='ListFoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listText', models.TextField()),
                ('blogPostNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.add_content_to_blog')),
            ],
        ),
    ]
