# Generated by Django 4.0.4 on 2022-11-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_add_content_to_blog_image_link_listofimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofimage',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
