# Generated by Django 4.1.3 on 2022-11-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_listofimage_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField(blank=True)),
                ('html', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
