# Generated by Django 4.1.3 on 2022-11-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_htmlcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CssFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('file_choice', models.FileField(upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
