# Generated by Django 4.1.3 on 2022-11-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_cssfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlcode',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
