# Generated by Django 4.1.3 on 2022-11-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_htmlcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_content_to_blog',
            name='img',
            field=models.ImageField(blank=True, upload_to='vlog'),
        ),
    ]
