# Generated by Django 4.1.3 on 2022-11-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_add_content_to_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_content_to_blog',
            name='image_link',
        ),
    ]
