# Generated by Django 4.1.3 on 2022-11-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_add_content_to_blog_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfocontent',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
