# Generated by Django 4.1.3 on 2022-11-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_listfocontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.TextField()),
                ('system', models.TextField()),
                ('meta', models.TextField()),
            ],
        ),
    ]
