# Generated by Django 4.1.3 on 2022-11-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_viewcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='date1',
            new_name='data1',
        ),
    ]
