# Generated by Django 4.1.3 on 2022-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rename_date1_viewcount_data1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus', models.TextField()),
                ('op1', models.TextField()),
                ('op2', models.TextField()),
                ('op3', models.TextField()),
                ('op4', models.TextField()),
                ('ans', models.TextField()),
                ('auth', models.TextField(blank=True, default='unknown')),
                ('auth_mail', models.TextField(blank=True)),
            ],
        ),
    ]
