# Generated by Django 4.1.3 on 2022-11-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_quiz_topic_quizs_catogory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizs',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='quizs',
            name='auth_mail',
        ),
        migrations.CreateModel(
            name='CreateQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.TextField()),
                ('auth_mail', models.TextField()),
                ('catogory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.quiz_topic')),
            ],
        ),
        migrations.AlterField(
            model_name='quizs',
            name='catogory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.createquiz'),
        ),
    ]
