# Generated by Django 4.1.3 on 2022-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_quizs_auth_remove_quizs_auth_mail_createquiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.TextField()),
                ('total', models.TextField()),
                ('output', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('email', models.TextField()),
            ],
        ),
    ]
